### ISSUE TITLE
evaluation metrics

### ISSUE THREAD

**Issue by chengjiali** [huangwl18/language-planner#1]
Hello,

Thanks for sharing your code! Could you share the code for calculating Executability and Correctness as well?

Thank you!

**Comment by huangwl18** [comment]
Thanks for the interest in the project! Executability is calculated by Evolving Graph Simulator of the [VirtualHome Environment](https://github.com/xavierpuigf/virtualhome/tree/5b8a652d7e11af97bf4f50c355af85ca664cae85). We plan to release the interface code soon. Correctness is evaluated by humans in the form of questionnaires, and there isn't code for it.

**Comment by chengjiali** [comment]
Thank you very much!

**Comment by TianHongZXY** [comment]
Hello, is there any plan to release the interface code for evaluation? Thank you!

**Comment by nikepupu** [comment]
Hi is there any plan to release the code?

**Comment by huangwl18** [comment]
Thanks for the interest and apologies that we haven't got to do the full cleaning of the code to release it. If you would still prefer a version anyway, please reach out to me via email (wenlongh@stanford.edu) and I'm happy to share the code.
